- name: deploy backend
  hosts: backend
  remote_user: ugamon29
  become: true
  tasks:
    - name: Install docker engine, nginx
      ansible.builtin.yum:
        name:
        - docker
        - nginx
        state: present
    
    - name: Install docker compose
      command: 'curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
      command: 'chmod +x /usr/local/bin/docker-compose'
    
    - name: Prepare a list of files to copy except node_modules
      command: find ./app -name node_modules -prune -o -type f -print
      delegate_to: localhost
      register: target_files
    
    - name: Cloning into the root from the git
      file:
        path: ~/movies-explorer-api/app
        state: directory

    - name: Copy files to root user directory
      copy:
        src: "{{ item }}"
        dest: ~/movies-explorer-api/app
      with_items: "{{ target_files.stdout_lines }}"
      tags:
        - copy
    
    - name: Copy production .env files
      copy:
        src: .env
        dest: ~/movies-explorer-api
    
    - name: Copy docker-compose files
      copy:
        src: docker-compose.yml
        dest: ~/movies-explorer-api
    
    - name: Build and start docker-compose files
      command: docker-compose up --build
      args:
        chdir: ~/movies-explorer-api