- name: deploy backend
  hosts: Ubuntu
  remote_user: ugamon29
  become: true
  tasks:
    - name: Install docker engine, nginx, git
      apt:
        name:
        - docker
        - nginx
        - git
        - docker-compose
        - certbot
        - python3-certbot-nginx 
        state: latest
  
    - name: Delete content & directory
      command: /bin/rm -rf /home/ugamon29/movies-explorer-api/* /home/ugamon29/movies-explorer-api/.* /home/ugamon29/movies-explorer-api
      
    - name: Cloning into the root from the git
      command: git clone https://github.com/ugamon/movies-explorer-api.git
      args:
        chdir: ~

    - name: Copy production .env files
      copy:
        src: .env
        dest: ~/movies-explorer-api
    
    - name: Copy docker-compose file
      copy:
        src: docker-compose.yml
        dest: ~/movies-explorer-api
    
    - name: Start docker engine
      command: systemctl start docker 
    
    - name: Build and start docker-compose files
      command: docker-compose build
      args:
        chdir: /home/ugamon29/movies-explorer-api
    
    - name: Launching the docker-compose infra
      command: docker-compose up -d
      args:
        chdir: /home/ugamon29/movies-explorer-api
    
    - name: Nginx configuration
      copy:
        src: ./nginx/default
        dest: /etc/nginx/sites-available/default
    
    - name: Enable nginx daemon
      command: systemctl enable --now nginx
    
    - name: Restart nginx daemon
      command: systemctl reload nginx
